### ISSUE TITLE
Get Depth and RGB Images from Kinect

### ISSUE THREAD

**Issue by pdr0663** [pgte/node-openni#25]
Are there any plans to fetch the depth or RGB images from the cameras into node?

I'd like to do some depth processing, without gestures or joints, just manipulating the depth map alone.

Paul

**Comment by gbougakov** [comment]
Try https://github.com/nguyer/node-kinect

**Comment by pdr0663** [comment]
@gbougakov Georg, thank you very much, this seems exactly what I want.

Paul
